name: build-documentation

on:
  release:
    # only run for stable releases
    types: [released]

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_TOKEN }}
        run: |
          gh workflow run --repo LibrePanel/Documentation build-and-deploy.yml -f type=tags -f ref=${{github.ref_name}}
